# prefix keys
unbind C-b
set-option -g prefix C-_                # Ctrl+/
set-option -g prefix2 M-z
bind-key C-_ send-prefix

bind-key M-z send-prefix -2
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# for copy pasting to clipboard from tmux
bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -r" \; display-message "Copied to selection"
bind-key -T copy-mode-vi Y send-keys -X copy-pipe "xclip -r -selection clipboard" \; display-message "Copied to clipboard"
bind-key C-p run-shell "xclip -o | tmux load-buffer - && tmux paste-buffer"
